version: '3.8'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: facility_booking_mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: facility-booking

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facility_booking_api
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: mongodb://mongodb:27017/facility-booking
      BCRYPT_SALT_ROUNDS: 12
      JWT_ACCESS_SECRET: your_jwt_access_secret_key_here_super_secure
      JWT_REFRESH_SECRET: your_jwt_refresh_secret_key_here_super_secure
      JWT_ACCESS_EXPIRES_IN: 1d
      JWT_REFRESH_EXPIRES_IN: 30d
      BACKEND_BASE_URL: http://localhost:5000
      CLIENT_BASE_URL: http://localhost:5173
    depends_on:
      - mongodb

volumes:
  mongo_data:
    driver: local
